# Generated by Django 4.2.5 on 2023-10-10 16:00

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mentorship", "0003_create_teacher_group_model"),
        ("studying", "0005_create_article_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Test name"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("time_limit", models.FloatField(verbose_name="Time limit")),
                (
                    "creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.teacher",
                    ),
                ),
                (
                    "topic_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studying.topic"
                    ),
                ),
            ],
            bases=(users.models.DateTimeMixin, models.Model),
        ),
    ]
