# Generated by Django 4.2.5 on 2023-10-10 16:01

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_system", "0001_create_article_test_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Question"
                    ),
                ),
                (
                    "test_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing_system.test",
                    ),
                ),
            ],
            bases=(users.models.DateTimeMixin, models.Model),
        ),
    ]
