version: "3.8"
services:
  db:
    container_name: pg_db
    image: postgres:latest
    volumes:
      - .learning_platform_db/postgres/:/var/lib/postgres/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    container_name: backend
    build:
      context: ././
      dockerfile: Dockerfile
    volumes:
      - .:/learning_platform
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
