# Generated by Django 4.2.5 on 2023-10-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0002_create_course_model"),
        ("mentorship", "0002_create_teacher_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Teacher group")),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studying.course",
                    ),
                ),
                ("student_id", models.ManyToManyField(to="mentorship.student")),
                (
                    "teacher_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentorship.teacher",
                    ),
                ),
            ],
        ),
    ]
