# Generated by Django 4.2.5 on 2023-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0003_create_topic_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="source/")),
            ],
        ),
    ]
