# Generated by Django 4.2.5 on 2023-10-10 15:57

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0003_create_teacher_group_model"),
        ("studying", "0004_create_article_image_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Topic name"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("is_completed", models.BooleanField(verbose_name="True/False")),
                (
                    "article_image_id",
                    models.ManyToManyField(to="studying.articleimage"),
                ),
                (
                    "creator_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentorship.teacher",
                    ),
                ),
                (
                    "topic_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studying.topic"
                    ),
                ),
            ],
            bases=(users.models.DateTimeMixin, models.Model),
        ),
    ]
